version: '3'
services: 
  controle-depesas:
    image: juliosouzaneto/controle-despesas
    ports: 
      - "8090:8082"
    depends_on:
      - mongodb
    networks: 
     - default
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
    
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks: 
     - default
    volumes:
      - /data/disk1/mongo/db:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure





